In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd 
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
os.getcwd()

'/Users/morarica/Developer/SepMe/Jupyters'

In [13]:
sepme_path = '../data/mturk_samples/phase1/graph_results/res_mturk_batch.csv'
res_path = '../data/mturk_samples/phase1/mturk_data.csv'

In [125]:
sep_df = pd.read_csv(sepme_path)
sep_df.columns = ['filename'] + list(sep_df.columns)[1:]
print(sep_df.columns)
sep_df.index = sep_df.filename
sep_df = sep_df.drop(['filename'], axis=1).stack().reset_index()
sep_df.columns = ['filename', 'method', 'value']

stuff = [row.split('_') for i,row in sep_df['method'].items() ]


new_stuff = []
for s in stuff: 
    ns = []

    if len(s)<=2:
        ns = ['del', 'n/a', 'mcec', -1]

    
    else:
        ns.append(s[0]) #graph_type
        try: 
            ns.append(float(s[1]))  #graph_param
            ns.append(s[2])  #graph_purity
            if len(s)==4:
                try:
                    ns.append(int(s[3]))  #class
                except ValueError:
                    ns.append(-1)  #class
            
            else:
                ns.append(-1)  #class

            if len(s)==5:
                ns[2] += '_' + s[4] #purity

        except ValueError:
            #print(s[1])
            ns.append('n/a')
            ns.append(s[1])  #graph_purity
            try:
                ns.append(int(s[2]))  #class
            except ValueError:
                ns.append(-1)  #class
            if len(s)==4:
                ns[2] += '_' + s[3]
        

    new_stuff.append(ns)
    #print('s {} - ns {}'.format(s,ns))
    if len(ns)!=4:
        print(ns)
    


sep_df['graph_type'] = [s[0] for s in new_stuff]
sep_df['graph_param'] = [s[1] for s in new_stuff]
sep_df['graph_purity'] = [s[2] for s in new_stuff]
sep_df['class'] = [s[3] for s in new_stuff]



sep_df.groupby(['graph_purity']).count()

sep_df = sep_df.loc[sep_df['class'].between(0,8)]

sep_df

Index(['filename', 'knn_2_ltcc_all', 'knn_2_ltcc_0', 'knn_2_ltcc_1',
       'knn_2_ltcc_2', 'knn_2_ltcc_3', 'knn_2_ltcc_4', 'knn_2_ltcc_5',
       'knn_2_ltcc_6', 'knn_2_ltcc_7',
       ...
       'cbsg_0.5_mv_8_false', 'cbsg_2_ltcc_8', 'cbsg_2_cp_8', 'cbsg_2_ce_8',
       'cbsg_2_mv_8_true', 'cbsg_2_mv_8_false', 'bt_0.02_ce_8', 'bt_0.02_ce_9',
       'bt_0.05_ce_8', 'bt_0.05_ce_9'],
      dtype='object', length=1276)

,filename,method,value,graph_type,graph_param,graph_purity,class
1,grid10_3d_RobPCA_1-2,knn_2_ltcc_0,0.390000,knn,2,ltcc,0
2,grid10_3d_RobPCA_1-2,knn_2_ltcc_1,0.333333,knn,2,ltcc,1
3,grid10_3d_RobPCA_1-2,knn_2_ltcc_2,0.113924,knn,2,ltcc,2
4,grid10_3d_RobPCA_1-2,knn_2_ltcc_3,0.056000,knn,2,ltcc,3
5,grid10_3d_RobPCA_1-2,knn_2_ltcc_4,0.048000,knn,2,ltcc,4
...,...,...,...,...,...,...,...
78372,fisheries_clusteredByEscapementTarget_tSNE_1-2,cbsg_0.5_cp_8,0.245238,cbsg,0.5,cp,8
78373,fisheries_clusteredByEscapementTarget_tSNE_1-2,cbsg_0.5_ce_8,0.509866,cbsg,0.5,ce,8
78376,fisheries_clusteredByEscapementTarget_tSNE_1-2,cbsg_2_ltcc_8,0.400000,cbsg,2,ltcc,8
78377,fisheries_clusteredByEscapementTarget_tSNE_1-2,cbsg_2_cp_8,0.133333,cbsg,2,cp,8
78378,fisheries_clusteredByEscapementTarget_tSNE_1-2,cbsg_2_ce_8,0.424680,cbsg,2,ce,8

In [14]:
res_df = pd.read_csv(res_path)
print(res_df.columns)
res_df.head()

Index(['1v1', 'AcceptTime', 'ApprovalTime', 'Approve',
       'AssignmentDurationInSeconds', 'AssignmentId', 'AssignmentStatus',
       'AutoApprovalDelayInSeconds', 'AutoApprovalTime', 'CreationTime',
       'Description', 'Expiration', 'HITId', 'HITTypeId', 'HITname',
       'Input.WorkerId', 'Input.class_set', 'Input.e', 'Input.file_name',
       'Input.i', 'Input.image_url', 'Keywords', 'Last30DaysApprovalRate',
       'Last7DaysApprovalRate', 'LifetimeApprovalRate', 'LifetimeInSeconds',
       'MaxAssignments', 'NumberOfSimilarHITs', 'Reject', 'RejectionTime',
       'RequesterAnnotation', 'RequesterFeedback', 'Reward', 'ShouldReward',
       'ShouldReward_2', 'SubmitTime', 'Title', 'WorkTimeInSeconds',
       'WorkerId', 'ap.1', 'ap.2', 'ap.3', 'ap.4', 'fileName', 'mp.1', 'mp.2',
       'mp.3', 'mp.4', 'pass1', 'pass2', 'pass3', 'pass4', 'passes', 'phase',
       'pneg1', 'pneg2', 'pneg3', 'pneg4', 'ppos1', 'ppos2', 'ppos3', 'ppos4',
       'sep1', 'sep2', 'sep3', 'sep4', 'sep5', 'sep6', 'sep7', 'sep8',
       'total_recordings', 'type'],
      dtype='object')

/Users/morarica/miniconda3/envs/SepMe/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (18,29,31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,1v1,AcceptTime,ApprovalTime,Approve,AssignmentDurationInSeconds,AssignmentId,AssignmentStatus,AutoApprovalDelayInSeconds,AutoApprovalTime,CreationTime,...,sep1,sep2,sep3,sep4,sep5,sep6,sep7,sep8,total_recordings,type
0,False,Fri Jan 10 09:12:27 PST 2020,NaN,NaN,7200,339ANSOTR67ZJVX549IPCDVGW8FKIS,Submitted,864000,Mon Jan 20 09:31:27 PST 2020,Fri Jan 10 09:06:37 PST 2020,...,17.0,12.0,23.0,NaN,NaN,NaN,NaN,NaN,18.0,semantic
1,False,Fri Jan 10 09:10:23 PST 2020,NaN,NaN,7200,39JEC7537V6MM35HB30A3J82Z11VCM,Submitted,864000,Mon Jan 20 09:10:34 PST 2020,Fri Jan 10 09:06:37 PST 2020,...,21.0,33.0,38.0,NaN,NaN,NaN,NaN,NaN,18.0,semantic
2,False,Fri Jan 10 09:12:08 PST 2020,NaN,X,7200,3DL65MZB8EK5KSJVGDB03FKGZ6ZCEY,Submitted,864000,Mon Jan 20 09:15:43 PST 2020,Fri Jan 10 09:06:37 PST 2020,...,78.0,73.0,76.0,NaN,NaN,NaN,NaN,NaN,18.0,semantic
3,False,Fri Jan 10 09:07:52 PST 2020,NaN,X,7200,3TDXMTX3CCZSKGCG25OO2UQYVDTI6J,Submitted,864000,Mon Jan 20 09:08:45 PST 2020,Fri Jan 10 09:06:37 PST 2020,...,86.0,83.0,88.0,NaN,NaN,NaN,NaN,NaN,18.0,semantic
4,False,Fri Jan 10 09:23:36 PST 2020,NaN,X,7200,3YDGXNSEO0ZLGNWPAVJIS7C6WQO84M,Submitted,864000,Mon Jan 20 10:37:08 PST 2020,Fri Jan 10 09:06:37 PST 2020,...,85.0,79.0,79.0,NaN,NaN,NaN,NaN,NaN,18.0,semantic

In [58]:
'all' not in stuff[0]

False